initial steps on complete data function
shannonpileggi/gtreg pull request #17
Opened 2021-12-08 21:09 UTC by shannonpileggi

still a WIP, not ready for review!

2021-12-15 00:38 UTC, shannonpileggi commented
Hi @ddsjoberg! I have a first pass at the `complete_data()` function. I can write more tests & checks, but before I do, can you review to see if you agree? (I haven't touched `tbl_adverse_events()` yet.)

- I created an additional helper function `get_unique()` to retrieve unique values of a variable.
- I realized that in supplying extra ids to get base n, we also need to know which strata the ids belong to. I modified the input ids argument `id_df` to take a frame of ids & strata.
- I couldn't get the cute `complete` + `nesting` combo to work, had to resort to `expand_grid` + `right_join`.

I'm open to any ideas or improvements, let me know what you think!

2021-12-15 02:02 UTC, ddsjoberg requested changes

2021-12-15 02:22 UTC, ddsjoberg commented
This example is from the unit tests. I don't think the complete data has all the needed observations. For example, ID1 needs a dummy observation for the bruising AE, right?

``` r
library(gtreg)

df1 <- tibble::tibble(
  patient_id = paste0("ID", c(1,1,2,3)),
  system_organ_class = "Blood and lymphatic system disorders",
  adverse_event = c("Anaemia", "Anaemia", "Anaemia", "Increased tendency to bruise"),
  grade = c(1, 1, 1, 2),
  trt = rep("A", 4)
)

e1 <- complete_data(
  data = df1,
  id = patient_id,
  ae = adverse_event,
  soc = system_organ_class,
  by = grade,
  strata = trt,
  id_df = data.frame(
    patient_id = paste0("ID", 1:5),
    trt = c(rep("A", 3),rep("B", 2))
  ),
  by_values = c("Unknown", 1:3)
)

df1
#> # A tibble: 4 x 5
#>   patient_id system_organ_class                   adverse_event      grade trt  
#>   <chr>      <chr>                                <chr>              <dbl> <chr>
#> 1 ID1        Blood and lymphatic system disorders Anaemia                1 A    
#> 2 ID1        Blood and lymphatic system disorders Anaemia                1 A    
#> 3 ID2        Blood and lymphatic system disorders Anaemia                1 A    
#> 4 ID3        Blood and lymphatic system disorders Increased tendenc~     2 A
e1$data_complete
#> # A tibble: 5 x 6
#>   id    strata ae                           soc                by    in_original
#>   <chr> <chr>  <chr>                        <chr>              <fct> <lgl>      
#> 1 ID1   A      Anaemia                      Blood and lymphat~ 1     TRUE       
#> 2 ID2   A      Anaemia                      Blood and lymphat~ 1     TRUE       
#> 3 ID3   A      Increased tendency to bruise Blood and lymphat~ 2     TRUE       
#> 4 ID4   B      Increased tendency to bruise Blood and lymphat~ dummy NA         
#> 5 ID5   B      Increased tendency to bruise Blood and lymphat~ dummy NA
```

<sup>Created on 2021-12-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2021-12-15 03:21 UTC, tgerke commented on R/get_unique.R
> +
I would hoist a return like this
```suggestion

  if (class(values) == "factor") {
    values <- as.character(values)
    return(values)
  }
  
  data %>%
    dplyr::distinct( {{var}} ) %>%
    dplyr::arrange( {{var}} ) %>%
    {if ( drop_na ) tidyr::drop_na(., {{var}} ) else . } %>%
    dplyr::pull( {{var}} )
  
}
```

2021-12-18 16:22 UTC, shannonpileggi commented on DESCRIPTION
> +    forcats,
thanks for the tip! added in commit to this PR

2021-12-18 16:26 UTC, shannonpileggi commented on R/complete_data.R
> +#' df_aes %>%
I believe this was resolved in your PR; we can add more examples as well. Did we decide that user is to pass quoted strings to argument rather than unquoted variable names?

2021-12-18 16:34 UTC, shannonpileggi commented on R/complete_data.R
> +complete_data <- function(data, id, ae, soc, by, strata,
completed with your PR

2021-12-18 16:36 UTC, shannonpileggi commented on R/complete_data.R
> +    dplyr::rename(!!!lst_name_recode) %>%
I think the renaming makes the programming easier, right? And if function is purely backstage it is safe to rename, if the function is user facing we could restore original names at end?

2021-12-18 16:37 UTC, shannonpileggi commented on R/complete_data.R
> +  initial_missing <- "Not entered"
agreed on both counts; both resolved with your PR

2021-12-18 17:01 UTC, ddsjoberg commented on R/complete_data.R
> +#' df_aes %>%
I thought that because this function is used internally, we didn't need to use the selectors twice. But it's not much overhead at all to add that functionality back in!

2021-12-18 17:02 UTC, ddsjoberg commented on R/complete_data.R
> +    dplyr::rename(!!!lst_name_recode) %>%
love it! sounds good to me!

2021-12-18 18:02 UTC, shannonpileggi commented on R/complete_data.R
> +#' df_aes %>%
Sounds good!  Let's chat order of operations and when we expect `.complete_ae_data()` to be called.

2021-12-18 18:09 UTC, shannonpileggi commented on R/get_unique.R
> +#' @export
ok i added this. never used it before and could use another eye to make sure it is as intended!

2021-12-18 18:35 UTC, shannonpileggi commented on R/get_unique.R
> +get_unique <- function(data, var, drop_na = TRUE){
agreed.  you might have some slicker solutions, but this functionality has been added in.

2021-12-18 18:51 UTC, shannonpileggi commented
Not sure how to add this as a comment in the review, but I think we could leave `by_values` flexible to input either character or numeric as they eventually get coerced to factor anyway.  Thoughts?

2021-12-18 18:53 UTC, shannonpileggi commented
What is the `, NA` doing in the testing?

2021-12-18 19:32 UTC, shannonpileggi commented
Just wanted to say purrr::compact() is cool!

2021-12-18 19:34 UTC, shannonpileggi commented on R/complete_data.R
> +  if (!is.null(id_df)) {
done

2021-12-18 19:34 UTC, shannonpileggi commented on R/complete_data.R
> +    dplyr::select(all_of(names(lst_name_recode)))
thanks for flagging!

2021-12-18 19:39 UTC, shannonpileggi commented on R/complete_data.R
> +      dplyr::arrange(strata, id)
i think this bit was re-factored and is no longer needed

2021-12-18 19:46 UTC, shannonpileggi commented on R/complete_data.R
> +      )
agreed we need a bajillion tests, but i think this specific bit of code has been refactored so resolving

2021-12-18 19:48 UTC, ddsjoberg commented
> Not sure how to add this as a comment in the review, but I think we could leave `by_values` flexible to input either character or numeric as they eventually get coerced to factor anyway. Thoughts?

Yeah, we can make that work!

2021-12-18 19:49 UTC, ddsjoberg commented
> What is the `, NA` doing in the testing? Does it mean expecting no errors?

exactly :)

2021-12-18 20:10 UTC, shannonpileggi commented on R/complete_data.R
> +    dplyr::slice_tail(n = 1) %>%
that makes sense, and i believe this was addressed with the PR. i added in `tab_vars` vector b/c i thought it might make it simpler, but i think it is making it harder, so i am totally open to rolling back that commit.

2021-12-18 20:11 UTC, shannonpileggi commented on R/complete_data.R
> +  tbl_ae_inputs <- as.list(environment())
let's keep discussing where and how `complete_ae_data` will be used to make sure we get this right

2021-12-18 20:12 UTC, shannonpileggi commented on R/complete_data.R
> +#' @param by Variable to split results by, e.g. report AEs by grade or attribution
probably - i think you addressed this with PR

2021-12-18 20:13 UTC, shannonpileggi commented
> This example is from the unit tests. I don't think the complete data has all the needed observations. For example, ID1 needs a dummy observation for the bruising AE, right?
> 
> ```r
> library(gtreg)
> 
> df1 <- tibble::tibble(
>   patient_id = paste0("ID", c(1,1,2,3)),
>   system_organ_class = "Blood and lymphatic system disorders",
>   adverse_event = c("Anaemia", "Anaemia", "Anaemia", "Increased tendency to bruise"),
>   grade = c(1, 1, 1, 2),
>   trt = rep("A", 4)
> )
> 
> e1 <- complete_data(
>   data = df1,
>   id = patient_id,
>   ae = adverse_event,
>   soc = system_organ_class,
>   by = grade,
>   strata = trt,
>   id_df = data.frame(
>     patient_id = paste0("ID", 1:5),
>     trt = c(rep("A", 3),rep("B", 2))
>   ),
>   by_values = c("Unknown", 1:3)
> )
> 
> df1
> #> # A tibble: 4 x 5
> #>   patient_id system_organ_class                   adverse_event      grade trt  
> #>   <chr>      <chr>                                <chr>              <dbl> <chr>
> #> 1 ID1        Blood and lymphatic system disorders Anaemia                1 A    
> #> 2 ID1        Blood and lymphatic system disorders Anaemia                1 A    
> #> 3 ID2        Blood and lymphatic system disorders Anaemia                1 A    
> #> 4 ID3        Blood and lymphatic system disorders Increased tendenc~     2 A
> e1$data_complete
> #> # A tibble: 5 x 6
> #>   id    strata ae                           soc                by    in_original
> #>   <chr> <chr>  <chr>                        <chr>              <fct> <lgl>      
> #> 1 ID1   A      Anaemia                      Blood and lymphat~ 1     TRUE       
> #> 2 ID2   A      Anaemia                      Blood and lymphat~ 1     TRUE       
> #> 3 ID3   A      Increased tendency to bruise Blood and lymphat~ 2     TRUE       
> #> 4 ID4   B      Increased tendency to bruise Blood and lymphat~ dummy NA         
> #> 5 ID5   B      Increased tendency to bruise Blood and lymphat~ dummy NA
> ```
> 
> Created on 2021-12-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

Agreed - I did not fully consider the input required by the tabulate function.

2021-12-18 20:15 UTC, shannonpileggi commented on R/get_unique.R
> +
This function has been refactored slightly.

2021-12-18 20:17 UTC, shannonpileggi commented on R/complete_data.R
> +  stopifnot(inherits(data, "data.frame"))
was this check removed? add back in?

2021-12-18 20:20 UTC, shannonpileggi reviewed
@ddsjoberg this bit might have been more trouble than it is worth - not sure. feel free to roll back.

if `ae` and `id` are the only required arguments, then we just option here for `soc` and `by`, as `strata` is implicitly tied to `id`?

2021-12-18 20:22 UTC, shannonpileggi commented
Is this PR getting hard to follow for anyone else? Would it be easier to merge and start new PR for fresh eyes?

2021-12-18 20:25 UTC, ddsjoberg commented on R/complete_data.R
> +  stopifnot(inherits(data, "data.frame"))
I think i removed it because it's an internal function, and the check will already appear in the `tbl_*()` function. We can add it back, since I do think we should export this function.

2021-12-18 20:29 UTC, ddsjoberg commented on R/complete_data.R
> +    dplyr::slice_tail(n = 1) %>%
I took a quick look at the `tab_vars`. I think there are two potential issues.
1. The `arrange()` and `group_by()` are both by `tab_vars`, but the `group_by()` cannot include `"by"`, as we are selecting the AE with the highest grade (ie most severe within by variable).
2. I saw that `..soc..` was removed. That column was meant to indicate the row that should be summarized when summarizing the SOC, which is not the same row as the AE summary. How do you envision identifying the appropriate row?

2021-12-18 20:33 UTC, ddsjoberg commented
> Is this PR getting hard to follow for anyone else? Would it be easier to merge and start new PR for fresh eyes?

YES! Can we sort out the tab_vars, then merge? 


> @ddsjoberg this bit might have been more trouble than it is worth - not sure. feel free to roll back.
> 
> if `ae` and `id` are the only required arguments, then we just option here for `soc` and `by`, as `strata` is implicitly tied to `id`?

I am not sure if I follow 100%? Let's revisit in the fresh PR?

2021-12-18 20:41 UTC, shannonpileggi commented
> > Is this PR getting hard to follow for anyone else? Would it be easier to merge and start new PR for fresh eyes?
> 
> YES! Can we sort out the tab_vars, then merge?
> 
> > @ddsjoberg this bit might have been more trouble than it is worth - not sure. feel free to roll back.
> > if `ae` and `id` are the only required arguments, then we just option here for `soc` and `by`, as `strata` is implicitly tied to `id`?
> 
> I am not sure if I follow 100%? Let's revisit in the fresh PR?

Agree, let's drop tab_vars and merg and fresh PR.  I'm getting into git trouble over here. I tried to roll back to previous commit before I added that but I don't think it worked.

2021-12-18 22:08 UTC, ddsjoberg approved these changes

2021-12-18 22:08 UTC, merged