add table modifications vignette
shannonpileggi/gtreg pull request #184
Opened 2022-09-08 17:58 UTC by shannonpileggi

**What changes are proposed in this pull request?**

Add a vignette to show how to modify table headers, footnotes, and captions.

**If there is an GitHub issue associated with this pull request, please provide link.**

Closes #96 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Has `NEWS.md` been updated with the changes from this pull request under the heading "`# gtreg (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Has the version number been incremented using `usethis::use_version(which = "dev")` 
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

2022-09-08 19:31 UTC, shannonpileggi commented
@ddsjoberg this article is ready for review, let me know what you think!

2022-09-08 20:23 UTC, ddsjoberg requested changes

2022-09-08 20:23 UTC, ddsjoberg commented on vignettes/articles/table-modifications.Rmd
> +# Overview
Rather than listing all the selection functions in an Overview, I would suggest this:
1. Start with an AE tables section.
2. Add each AE selector to a table with two columns. The first lists the selecting function, and the second a brief description. 
3. Followup with a graphic of a table, highlighting the columns that are selected by each selector. Could it be a cute GIF that blurs the columns _not_ selected by a selector? That could be cute!

2022-09-08 20:23 UTC, ddsjoberg commented on vignettes/articles/table-modifications.Rmd
> +tbl4 |>
Replace all base pipes with magrittr

2022-09-09 13:56 UTC, shannonpileggi commented on vignettes/articles/table-modifications.Rmd
> +tbl4 |>
done

2022-09-09 13:57 UTC, shannonpileggi commented on vignettes/articles/table-modifications.Rmd
> +For all `modify_` functions, formatting is applied via markdown
yeah maybe a bit too much detail?

2022-09-12 19:05 UTC, shannonpileggi commented
@ddsjoberg this is ready for review again

2022-09-12 21:14 UTC, ddsjoberg approved these changes
looks fantastic! added just a few minor comments. update or don't update as you like! ❤️

2022-09-12 21:14 UTC, ddsjoberg commented on R/selectors.R
> +#' See the Table modifications article for examples.
Add link to dev site?

2022-09-12 21:14 UTC, ddsjoberg commented on vignettes/articles/table-modifications.Rmd
> +![](gtreg-modify.gif)
- Make the caption bold to match the headers?
- I feel this fits better beneath the gt table you created?

2022-09-12 21:14 UTC, ddsjoberg commented on vignettes/articles/table-modifications.Rmd
> +tibble::tribble(
Make column center aligned?

2022-09-12 21:14 UTC, ddsjoberg commented on vignettes/articles/table-modifications.Rmd
> +  knitr::kable(
you could make this a gt table so the styling matches the rendered gtreg tables too

2022-09-12 23:28 UTC, shannonpileggi commented on R/selectors.R
> +#' See the Table modifications article for examples.
done

2022-09-12 23:36 UTC, shannonpileggi commented on vignettes/articles/table-modifications.Rmd
> +  knitr::kable(
k see if you like the changes

2022-09-12 23:36 UTC, shannonpileggi commented on vignettes/articles/table-modifications.Rmd
> +tibble::tribble(
done

2022-09-12 23:55 UTC, shannonpileggi commented on vignettes/articles/table-modifications.Rmd
> +![](gtreg-modify.gif)
k i moved it but didn't do the bolding.

2022-09-12 23:58 UTC, shannonpileggi commented
@ddsjoberg comments addressed

2022-09-13 01:14 UTC, merged