Update to pkgdown and re-exporting some gtsummary functions
shannonpileggi/gtreg pull request #37
Opened 2021-12-22 00:52 UTC by ddsjoberg

- The beginnings of a pkgdown site have been added (this can of course be updated)
- Re-exporting gtsummary functions

closes #30 
closes #25

2021-12-22 16:02 UTC, ddsjoberg commented on DESCRIPTION
> +           comment = c(ORCID = "YOUR-ORCID-ID")),
@shannonpileggi can you add your ORCID here, or delete the comment?

2021-12-23 19:29 UTC, shannonpileggi requested changes
Thanks for keeping this moving!

2021-12-23 19:29 UTC, shannonpileggi commented on DESCRIPTION
> +           comment = c(ORCID = "YOUR-ORCID-ID")),
```suggestion
person("Shannon", "Pileggi", , "shannon@pipinghotdata.com", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-7732-4164")),
```

2021-12-23 19:29 UTC, shannonpileggi commented on man/gtreg-package.Rd
> +\strong{Maintainer}: Shannon Pileggi \email{first.last@example.com} (\href{https://orcid.org/YOUR-ORCID-ID}{ORCID})
This is auto generated from `DESCRIPTION` right? So I don't need to edit this?

2021-12-23 19:29 UTC, shannonpileggi commented on DESCRIPTION
>  Title: What the Package Does (One Line, Title Case)
```suggestion
GT Backed Regulatory Tables For Clinical Research
```

A working title?

2021-12-23 19:29 UTC, shannonpileggi commented on DESCRIPTION
> +           comment = c(ORCID = "YOUR-ORCID-ID")),
Wasn't sure if I had one, but found it!

2021-12-23 19:45 UTC, ddsjoberg commented on man/gtreg-package.Rd
> +\strong{Maintainer}: Shannon Pileggi \email{first.last@example.com} (\href{https://orcid.org/YOUR-ORCID-ID}{ORCID})
right!

2021-12-23 19:46 UTC, ddsjoberg commented on DESCRIPTION
>  Title: What the Package Does (One Line, Title Case)
We should look up the CRAN rules...i think they have a policy on how to refer to another package's name in a title or description.

2021-12-23 20:06 UTC, ddsjoberg commented on DESCRIPTION
> +Title: GT Backed Regulatory Tables For Clinical Research
Found it! "The mandatory ‘Title’ field should give a short description of the package. Some package listings may truncate the title to 65 characters. It should use title case (that is, use capitals for the principal words: tools::toTitleCase can help you with this), not use any markup, not have any continuation lines, and not end in a period (unless part of …). Do not repeat the package name: it is often used prefixed by the name. Refer to other packages and external software in single quotes, and to book titles (and similar) in double quotes."

I'll update it

2021-12-23 21:07 UTC, shannonpileggi approved these changes
Thanks for the title adjustment, this looks great!

2021-12-23 21:16 UTC, merged