Adding `tbl_ae_binary()`
shannonpileggi/gtreg pull request #45
Opened 2021-12-23 23:13 UTC by ddsjoberg

- Adding function `tbl_ae_binary()` 
- I don't love the name, but can be addressed later 🤷🏼 
closes #28

2021-12-23 23:19 UTC, shannonpileggi commented
Ha, regarding the name!  Yes, it isn't quite binary.  More like...

`tbl_ae_subset()`
`tbl_ae_zoom()`
`tbl_ae_compare()`
`tbl_ae_focus()`

2021-12-23 23:52 UTC, ddsjoberg commented
> I want to make sure I understand how you are thinking about the word `binary`, and what are the expectations for the `include` variable. 

Yep, all variables passed in `include=` must be logical/binary.

2021-12-24 18:53 UTC, ddsjoberg commented
I'll update the function name to `tbl_ae_focus()`! I prefer it to the current name for sure

2021-12-27 15:22 UTC, shannonpileggi requested changes
This function is awesome! It will allow so many custom tables!

2021-12-27 15:22 UTC, shannonpileggi commented on R/tbl_ae_focus.R
> +#' Tabulate AE Binary Summaries
```suggestion
#' Tabulate AE Focused (Dichotomous) Summaries
```

2021-12-27 15:22 UTC, shannonpileggi commented on R/tbl_ae_focus.R
> +#' Summarize AE data that is binary or dichotomous. For example, report the
```suggestion
#' Summarize dichotomous AE data. For example, report the
```

2021-12-27 15:57 UTC, shannonpileggi reviewed
Go ahead and merge or update tests / examples with updated data first?

2021-12-27 16:34 UTC, merged