Update get unique
shannonpileggi/gtreg pull request #53
Opened 2021-12-28 03:44 UTC by shannonpileggi

2021-12-28 13:22 UTC, ddsjoberg commented
The PR looks great!

This function isn't being used internally any longer. Do you want to export it as a utility?

2021-12-28 13:22 UTC, ddsjoberg requested changes
🥳

2021-12-28 13:22 UTC, ddsjoberg commented on R/get_unique.R
>  get_unique <- function(data, var, drop_na = TRUE, keep_fct_levels = TRUE){
Do you want to keep the name as `get_unique()`, or use the dot prefix we have for other utility functions?

2021-12-28 13:22 UTC, ddsjoberg commented on R/get_unique.R
> +  if (inherits(data[["var"]], "factor") & keep_fct_levels) {
I think something like this is typically safer (in case a user passes a non-logical to `keep_fct_levels=`). Also, you can use the `&&` to stop the evaluation if the first condition is not TRUE.

```r
inherits(data[["var"]], "factor") && isTRUE(keep_fct_levels)
```

2021-12-30 19:47 UTC, shannonpileggi commented
Per previous discussion, this function is no longer used and has been removed from package.  This has been added to [croquet](https://github.com/pcctc/croquet) in case it is useful again in future.

2021-12-30 19:49 UTC, shannonpileggi commented
@ddsjoberg I pulled upstream, deleted R function and test file, & re-documented (don't think that did anything) so 🤞 this can be merged.

2021-12-30 20:00 UTC, ddsjoberg approved these changes
looks good!

2021-12-31 20:34 UTC, merged