Added `sort=` argument to all functions
shannonpileggi/gtreg pull request #71
Opened 2022-01-10 02:04 UTC by ddsjoberg

@shannonpileggi can you take a look at this? what do you think of the user experience here? can be better?

- [ ] add unit tests
closes #2

2022-01-10 18:39 UTC, shannonpileggi requested changes
We should also add some tests, but this might be best after #67 is complete.

2022-01-10 18:39 UTC, shannonpileggi commented on R/tbl_ae.R
> +#'  order.
The `sort` argument applies only to ae overall (when ae is specified) or ae within soc (when both ae and soc are specified).  Maybe the documentation could be amended like:

```suggestion
#' @param sort Controls order AEs appear.  When `ae` is specified without `soc`, applies to AEs overall. When `ae` is #' specified with `soc`, applies to AEs within SOCs.  Default is
#'  `"alphanumeric"` for alphabetical sorting. `sort = "frequency"` will sort in decreasing frequency
#'  order.
```

2022-01-10 18:40 UTC, shannonpileggi commented on R/tbl_ae.R
> +#'  order.
Or I am wondering if I tested this enough to understand what was happening...

2022-01-10 18:45 UTC, shannonpileggi commented
Other things I am thinking about, that might be worth a quick chat, is:

- would it be worthwhile to have sort_ae & sort_soc separate controls? or overkill?
- what happens if ae or soc's are input as a factor?  preserving that might be a nice feature if users have a specific order in mind

2022-01-10 18:57 UTC, ddsjoberg commented
> * would it be worthwhile to have sort_ae & sort_soc separate controls? or overkill?
> * what happens if ae or soc's are input as a factor?  preserving that might be a nice feature if users have a specific order in mind

I think overkill to add two arguments for sorting. If the users have a specific ordering in mind, they can make the AE or SOC a factor, and the factor ordering is preserved.

2022-01-10 20:03 UTC, shannonpileggi commented
Sounds good!  I was just checking a few combinations with this test set.

```
df2 <-
  tibble::tibble(
    patient_id = paste0("ID", 1:9),
    system_organ_class = c("Fruit", "Fruit", "Fruit", "Veg", "Veg", "Veg", "Veg", "Bread", "Bread"),
    adverse_event = c("apple",  "banana", "banana", "artichoke", "spinach", "spinach", "spinach", "ciabatta", "sourdough"),
    grade = rep(1, 9),
    trt = rep("A", 9)
  )
```

with no `sort` specified, factor levels are preserved.
```
  df2 %>%
    mutate(
      adverse_event = forcats::fct_relevel(adverse_event, "sourdough", "banana")
    ) %>%
    tbl_ae(
      id = patient_id,
      ae = adverse_event,
      statistic = "{n}"
    )
```

![image](https://user-images.githubusercontent.com/17747575/148831044-2812c34e-2348-44db-9f9d-a2adfc4f8100.png)

when `sort = "frequency"` is applied, sort overrides factor levels.

```
  df2 %>%
    mutate(
      adverse_event = forcats::fct_relevel(adverse_event, "sourdough", "banana")
    ) %>%
    tbl_ae(
      id = patient_id,
      ae = adverse_event,
      statistic = "{n}",
      sort = "frequency"
    )
```
![image](https://user-images.githubusercontent.com/17747575/148831267-bcd8cd84-adfd-4268-b9f6-cf221a62b073.png)

when `sort = "alphanumeric"` the factor levels are preserved and alphanumeric does not override.

````
  df2 %>%
    mutate(
      adverse_event = forcats::fct_relevel(adverse_event, "sourdough", "banana")
    ) %>%
    tbl_ae(
      id = patient_id,
      ae = adverse_event,
      statistic = "{n}",
      sort = "alphanumeric"
    )
```

![image](https://user-images.githubusercontent.com/17747575/148831459-7aa975b8-d8f6-4251-a0d5-a6076c47ba24.png)

what should be the expected behavior here? to override, warn, or preserve factors?

2022-01-10 20:08 UTC, ddsjoberg commented
alphanumeric is the default, and preserves the inherent ordering (be that a character vector or a factor). I think this is expected. Do you think it should be something else?

2022-01-10 21:06 UTC, shannonpileggi commented
as a user, i might expect alphanumeric to overwrite factor ordering if it is present, so lets just add the behavior to the documentation!

2022-01-10 21:10 UTC, ddsjoberg commented
> as a user, i might expect alphanumeric to overwrite factor ordering if it is present, so lets just add the behavior to the documentation!

ok sounds good. @shannonpileggi can you update it ?

2022-01-10 21:14 UTC, shannonpileggi commented
not yet!  one  more thing, another option might be to call it `sort = "internal"` instead of alphanumeric to indicate it uses whatever internal mechanism it comes with (alphanumeric for character, factor levels for factor).

2022-01-10 21:18 UTC, ddsjoberg commented
> not yet! one more thing, another option might be to call it `sort = "internal"` instead of alphanumeric to indicate it uses whatever internal mechanism it comes with (alphanumeric for character, factor levels for factor).

Hmmm, for me that is more confusing having a 3rd option. But I'll leave it up to you to add whatever your preference is! For me, factors are sorted according to their assigned order so I would expect that to persist in the function.

2022-01-11 01:05 UTC, shannonpileggi approved these changes
Ok, I updated docs a bit and added a few more lazy tests.  Let me know if you want any further revisions!

2022-01-11 01:29 UTC, merged

2022-01-13 05:03 UTC, shannonpileggi commented
I think we need to test sorting a bit more on external data sets.